export const exerciseNames = [
  "snatch",
  "clean and jerk",
  "clean",
  "split jerk",
  "comp snatch",
  "comp clean and jerk",
  "comp total",
  "power snatch",
  "power clean",
  "power jerk",
  "push press",
  "back squat",
  "front squat",
  "overhead squat",
  "hang snatch",
  "hang clean",
  "block snatch",
  "block clean",
  "muscle snatch",
  "strict press",
  "snatch balance",
  "snatch pull",
  "clean pull",
  "snatch deadlift",
  "clean deadlift",
  "pushups",
  "pull-ups",
  "dips",
]
